### ISSUE TITLE
GIFs cause the API to throw an error

### ISSUE THREAD

**Issue by sks316** [KuroZen/r34-json-api#3]
**Describe the bug**
Going to https://custom-r34-api.herokuapp.com/posts?tags=gif produces an Application Error

**To Reproduce**
1. Go to https://custom-r34-api.herokuapp.com/posts?tags=gif
2. See error

**Expected behavior**
The API responds with the usual JSON

**Screenshots**
![screenie-2019-10-11-17_21_23](https://user-images.githubusercontent.com/28124909/66688363-e4646d80-ec4b-11e9-97f1-ff5383ca0c23.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Mozilla Firefox
 - Version: 69.0.2

**Smartphone (please complete the following information):**
Haven't tried to access it here

**Additional context**
I use this API in a project of mine ([sks316/mewtwo-bot](https://github.com/sks316/mewtwo-bot)), and the error also occurs there.

**Comment by sks316** [comment]
@KuroZenZen

**Comment by sks316** [comment]
Seems to be fixed now.

**Comment by kurozenzen** [comment]
> **Describe the bug**
> Going to https://custom-r34-api.herokuapp.com/posts?tags=gif produces an Application Error
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to https://custom-r34-api.herokuapp.com/posts?tags=gif
> 2. See error
> 
> **Expected behavior**
> The API responds with the usual JSON
> 
> **Screenshots**
> ![screenie-2019-10-11-17_21_23](https://user-images.githubusercontent.com/28124909/66688363-e4646d80-ec4b-11e9-97f1-ff5383ca0c23.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 18.04 LTS
> * Browser: Mozilla Firefox
> * Version: 69.0.2
> 
> **Smartphone (please complete the following information):**
> Haven't tried to access it here
> 
> **Additional context**
> I use this API in a project of mine ([sks316/mewtwo-bot](https://github.com/sks316/mewtwo-bot)), and the error also occurs there.

Yeah... Sorry about that. r34 changed some stuff on their end and broke everything.

**Comment by kurozenzen** [comment]
Oh wait, you are still on the old version...
I really have to update the Readme.

Newer versions of the api deployed here:
```
https://r34-json.herokuapp.com
https://r34-api-clone.herokuapp.com
```
Two in case something unexpected nukes the first one. **Some stuff changed. Mainly stability and posts now return how many results there are.**

Feel free to stay on the old one. I am not gonna take it offline anytime soon.
