### ISSUE TITLE
Cannot sort items

### ISSUE THREAD

**Issue by aucoq** [KuroZen/r34-json-api#6]
@kurozenzen Sorry, I couldn't figure out how to create an issue on your new repository.

Using the "sort" tag doesn't seem to work anymore. Placing it at the end of a search will return 0 results. Placing it anywhere else seems to ignore the tag and simply sorts by newest first.

Examples:

https://r34-json.herokuapp.com/posts?tags=+sort:score:desc+pixar - returns results ordered newest first (instead of by score:desc)

https://r34-json.herokuapp.com/posts?tags=+pixar+sort:score:desc - returns 0 results

**Comment by kurozenzen** [comment]
Yep. I noticed that. I will investigate more but i think its broken on rule34.xxx, which i use as the backend for this api. Ic that is the case i can't really do much.

**Comment by kurozenzen** [comment]
As I thought... It was broken on rule34.xxx as well. It should be fixed now.

**Comment by aucoq** [comment]
Thanks!
