### ISSUE TITLE
API offline

### ISSUE THREAD

**Issue by 4A6F6F6E61** [KuroZen/r34-json-api#8]
**Describe the bug**
The Heroku API is offline/doesn't work anymore.

**To Reproduce**
1. Make a request

**Expected behavior**
JSON data

**Screenshots**
![image](https://user-images.githubusercontent.com/32982128/149159729-9a9fef49-aee7-4d59-94db-e4da1887b12d.png)

**Desktop**
 - OS: Windows 11 Pro 64bit
 - Browser: Firefox
 - Version: 95.0.2 (64-bit)

**Comment by Void-n-Null** [comment]
I am also having this issue, it seems to come about periodically. Its possible that this is an issues with the host of the API Wrapper not setting up the Wrapper correctly and causing errors that means the application needs to be manually restarted
